services:
  auth-service:
    build:
      context: ./bzhspauth/app
      dockerfile: Dockerfile-local
    ports:
      - "8082:8082"
    volumes:
      - ./bzhspauth/app:/app
    environment:
      - AUTH_DB_HOST=${AUTH_DB_HOST}
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_TIMEZONE=${TIMEZONE}
      - GIN_MODE=${GIN_MODE}
      - JWT_SECRET=${JWT_SECRET}
    entrypoint:
      - ./bzhspauth/app/scripts/dev-entrypoint.sh
    depends_on:
      - db-auth
  db-auth:
    image: postgres:17
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - ./volumes/auth-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"


  product-service:
    build:
      context: ./bzhspproduct/app
      dockerfile: Dockerfile-local
    ports:
      - "8081:8081"
    volumes:
      - ./bzhspproduct/app:/app
    environment:
      - PRODUCT_DB_HOST=${PRODUCT_DB_HOST}
      - PRODUCT_DB_USER=${PRODUCT_DB_USER}
      - PRODUCT_DB_PASSWORD=${PRODUCT_DB_PASSWORD}
      - PRODUCT_DB_NAME=${PRODUCT_DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_TIMEZONE=${TIMEZONE}
      - GIN_MODE=${GIN_MODE}
    entrypoint:
      - ./bzhspproduct/app/scripts/dev-entrypoint.sh
    depends_on:
      - db-product
  db-product:
    image: postgres:17
    environment:
      POSTGRES_USER: ${PRODUCT_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD}
      POSTGRES_DB: ${PRODUCT_DB_NAME}
    volumes:
      - ./volumes/product-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
