name: Update submodule

on:
  pull_request:
    branches: [dev]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Update submodule'
      run: |
        git submodule update --init --recursive
        git submodule update --remote --merge
        git pull --recurse-submodules
        
