name: Update submodule

on:
  pull_request:
    branches: [dev]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          ssh-key: ${{ secrets.ACTIONS_SSH_KEY }}
          submodules: 'recursive'
          persist-credentials: false 
        
      - name: 'Update submodules'
        run: |
          git submodule update --init --recursive
          git submodule update --remote --merge
          git pull --recurse-submodules
          git submodule foreach git pull origin dev
          git add bzhspauth bzhspproduct bzhspfront bzhspdeploy
          git commit -m "Update submodules to latest commits on dev branch"
          git push origin HEAD:${{ github.head_ref }}

